# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
    build:
        docker:
            # specify the version you desire here
            - image: circleci/android:api-28-node8-alpha
        working_directory: ~/repo

        steps:
            - checkout

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v2-dependencies-{{ checksum "package.json" }}

            - run: npm install

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}

            - run: npm run build

            - run: |
                  git clone "git@github.com:monya-wallet/dev.git" dev
                  git config --global user.name "circleci"
                  git config --global user.email "circleci@chatbox-inc.com"
                  cp -r docs/wallet/* dev
                  cp -r cordovaProj/www/* dev/cwww
                  cd dev
                  git add .
                  git commit -m "[ci skip] build on circle ci"
                  git push origin master
                  cd ..

            - run: |
                  sudo npm i -g cordova@7.1.0
                  wget https://services.gradle.org/distributions/gradle-4.1-bin.zip -qO gradle.zip
                  sudo unzip gradle.zip -d /opt
                  export PATH="$PATH:/opt/gradle-4.1/bin/"
                  sudo echo $ANDROID_SDK_LICENSE_VOLUMES > $ANDROID_HOME/licenses/android-sdk-license
                  sdkmanager tools "build-tools;28.0.3" "platform-tools" "platforms;android-28"
                  cd cordovaProj
                  npm i
                  cordova platform add android
                  cordova build android --release

            - store_artifacts:
                  path: cordovaProj/platforms/android/build/outputs/apk/
    publish:
        docker:
            # specify the version you desire here
            - image: circleci/android:api-28-node8-alpha
        working_directory: ~/repo

        steps:
            - checkout

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v2-dependencies-{{ checksum "package.json" }}

            - run: npm install

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}

            - run: npm run build

            - run: |
                  git clone "git@github.com:monya-wallet/monya-wallet.github.io.git" release
                  git config --global user.name "circleci"
                  git config --global user.email "circleci@chatbox-inc.com"
                  cp -r docs/wallet/* release/wallet
                  cd release
                  git add .
                  git commit -m "[ci skip] build on circle ci"
                  git push origin master
                  cd ..

            - run: |
                  sudo npm i -g cordova@7.1.0
                  wget https://services.gradle.org/distributions/gradle-4.1-bin.zip -qO gradle.zip
                  sudo unzip gradle.zip -d /opt
                  export PATH="$PATH:/opt/gradle-4.1/bin/"
                  sudo echo $ANDROID_SDK_LICENSE_VOLUMES > $ANDROID_HOME/licenses/android-sdk-license
                  sdkmanager tools "build-tools;28.0.3" "platform-tools" "platforms;android-28"
                  cd cordovaProj
                  npm i
                  cordova platform add android
                  cordova build android --release
            - store_artifacts:
                  path: cordovaProj/platforms/android/build/outputs/apk/
            - store_artifacts:
                  path: chrome_extension.zip
workflows:
    version: 2
    build_and_cordova:
        jobs:
            - build:
                  filters:
                      branches:
                          only: master
            - publish:
                  filters:
                      branches:
                          only: release
